- name: install apt packages
  apt:
    pkg={{ item }}
    state=latest
  with_items:
    - git
    - python-dev
    - python-setuptools
    - python-virtualenv
    - python-pip

- name: install pip packages
  pip:
    name={{ item }} state=latest
    # depending on version of pip, this may also need:
    # extra_args=--no-use-wheel
  with_items:
    - setuptools
    - pip

- name: install pip packages into venv
  pip:
    name={{ item }}
    state=latest
    virtualenv=/var/venv/gatewatch/
  with_items:
    - setuptools
    - pip
#   - 'git+{{ git_repo }}#egg=gatewatch'

- name: create app config dir
  file:
    dest=/var/venv/gatewatch/var/gatewatch-instance
    state=directory

- name: deploy app config
  template:
    src=config.py
    dest=/var/venv/gatewatch/var/gatewatch-instance/gatewatch_config.py
