- name: install apt packages
  apt:
    pkg={{ item }}
    state=latest
  with_items:
    - git
    - python-dev
    - python-setuptools
    - python-pip

- name: install pip packages
  pip:
    name={{ item }} state=latest
    extra_args='--allow-external lazr.authentication --allow-unverified lazr.authentication'
  with_items:
    - setuptools
    - pip
    - 'git+ssh://dolph@git.dolphm.com/home/dolph/repos/gatewatch#egg=gatewatch'

- name: create app config dir
  file:
    dest=/etc/gatewatch
    state=directory

- name: deploy app config
  template:
    src=config.py
    dest=/etc/gatewatch/gatewatch.conf.py
