#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

# don't activate screensaver
xset s off

# disable DPMS (Energy Star) features
xset -dpms

# don't blank the video device
xset s noblank

# invoke global X session script
. /etc/X11/Xsession
