- hosts: all
  sudo: True
  sudo_user: gatewatch
  tasks:
    - name: fetch app repo
      git:
        repo=ssh://dolph@git.dolphm.com/home/dolph/repos/gatewatch
        dest=~/gatewatch

    - name: install app
      pip:
        name=~/gatewatch
        state=latest
        virtualenv=~/venv
        extra_args='--allow-external lazr.authentication --allow-unverified lazr.authentication'

- hosts: all
  tasks:
    - name: restart supervised processes
      supervisorctl:
        name={{ item }}
        state=restarted
      with_items:
        - gunicorn
        - celery
        - celery-beat
