- hosts: all
  tasks:
    - name: install apt packages
      apt:
        pkg=nginx

    - name: deploy nginx config
      template:
        src=templates/nginx.vhost
        dest=/etc/nginx/sites-enabled/default
      notify: restart nginx

    - name: ensure nginx is running
      service:
        name=nginx
        enabled=yes
        state=started
  handlers:
    - name: restart nginx
      service:
        name=nginx
        state=reloaded
