- hosts: all
  tasks:
    - name: install apt packages
      apt:
        pkg={{ item }}
      with_items:
        - git
        - nginx
        - python-dev
        - python-setuptools
        - python-virtualenv
        - redis-server
        - supervisor

    - name: install pip
      action: easy_install name=pip

    - name: create ssh dir
      file:
        path=/root/.ssh
        state=directory

    - name: install public deploy key
      copy:
        src=~/.ssh/deploy.pub
        dest=/root/.ssh/id_rsa.pub

    - name: install private deploy key
      copy:
        src=~/.ssh/deploy
        dest=/root/.ssh/id_rsa

    - name: install git.dolphm.com known host
      copy:
        src=files/known_hosts
        dest=/root/.ssh/known_hosts

    - name: install pip packages into venv
      pip:
        name={{ item }} state=latest
        virtualenv=/opt/gatewatch/venv
      with_items:
        - pip
        - celery
        - gunicorn

    - name: install app into venv
      pip:
        name={{ item }} state=latest
        virtualenv=/opt/gatewatch/venv
        extra_args='--allow-external lazr.authentication --allow-unverified lazr.authentication'
      with_items:
        - 'git+ssh://dolph@git.dolphm.com/home/dolph/repos/gatewatch#egg=gatewatch'

    - name: create directories
      file:
        dest={{ item }}
        state=directory
        owner=www-data
        group=www-data
        mode=0700
      with_items:
        - /etc/gatewatch
        - /var/log/gatewatch
        - /tmp/gatewatch

    - name: deploy app config
      template:
        src=templates/config.py
        dest=/etc/gatewatch/gatewatch.conf.py
        owner=www-data
        group=www-data
        mode=0700

    - name: deploy celery config
      template:
        src=templates/supervisor.celery.conf
        dest=/etc/supervisor/conf.d/celery.conf
      notify:
        - restart celery

    - name: deploy gunicorn config
      template:
        src=templates/supervisor.gunicorn.conf
        dest=/etc/supervisor/conf.d/gunicorn.conf
      notify:
        - restart gunicorn

    - name: ensure supervisor is running
      service:
        name=supervisor
        enabled=yes
        state=started

    - name: ensure supervised processes are present
      supervisorctl:
        name={{ item }}
        state=present
      with_items:
        - celery
        - celery-beat
        - gunicorn

    - name: deploy nginx config
      template:
        src=templates/nginx.vhost
        dest=/etc/nginx/sites-enabled/default
      notify: restart nginx

    - name: ensure nginx is running
      service:
        name=nginx
        enabled=yes
        state=started

  handlers:
    - name: restart celery
      supervisorctl:
        name={{ item }}
        state=restarted
      with_items:
        - celery
        - celery-beat

    - name: restart gunicorn
      supervisorctl:
        name=gunicorn
        state=restarted

    - name: restart nginx
      service:
        name=nginx
        state=reloaded
