- hosts: all
  tasks:
    - name: install apt packages
      apt:
        pkg={{ item }}
      with_items:
        - supervisor

    - name: install pip packages
      pip:
        name={{ item }} state=latest
        virtualenv=/opt/gatewatch/venv
      with_items:
        - celery

    - name: deploy celery config
      template:
        src=supervisor.celery.conf
        dest=/etc/supervisor/conf.d/celery.conf
      notify:
        - restart celery
        - restart celery-beat

    - name: ensure celery is started
      supervisorctl:
        name={{ item }}
        state=started
      with_items:
        - celery
        - celery-beat
  handlers:
    - name: restart celery-beat
      supervisorctl:
        name=celery-beat
        state=restarted

    - name: restart celery
      supervisorctl:
        name=celery
        state=restarted
