# this playbook bootstraps a raspberry pi for use as automated browser kiosk

- hosts: all
  user: pi
  sudo: True
  tasks:
    - name: default to portrait orientated display
      copy:
        src=templates/boot.config.txt
        dest=/boot/config.txt

    - name: update apt cache
      sudo: yes
      apt:
        update_cache=yes

    - name: install packages
      apt:
        pkg={{ item }}
      with_items:
        - unclutter # hide the mouse cursor
        - chromium # we need a browser with kiosk mode
        - x11-xserver-utils # to disable screen blanking

    - name: start chrome in kiosk mode on startup
      copy:
        src=templates/lxde_autostart
        dest=/etc/xdg/lxsession/LXDE/autostart
        owner=root
        group=root
        mode=0644

    - name: restart raspberry pi
      command: shutdown -r now "ansible playbook completing..."
      async: 0
      poll: 0
      ignore_errors: true
